#
###################################
# Site wide configuration
####################################
#
title: Graham Mackie (.com)
email: graham.mackie@gmail.com
description: A simple blog/resume, created using Jekyll, hosted on kubernetes with Gitea CI/CD!
url: https://grahammackie.com # the base hostname & protocol for your site
keywords: ["Programming", "Music", "Maker", "Hacking"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Los_Angeles
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Graham
  avatar: leonids-logo.png
  job: "Software Developer/Manager"
  bio: "A jack-of-all-trades developer, recently converted to management who loves to solve interesting problems. Working for Amazon in Seattle, Washington, USA."
  email: graham.mackie@gmail.com
  disqus-shortname: #username
  twitter: grahammackie
  facebook: grahammackie
  google:
    plus: 
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: gmackie
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: gmackie
  xing: #username
  instagram: gmackienw
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: deathfudge
  dribbble: #username
  youtube: #username
  soundcloud: gmack-attack
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
